import { db } from '@/db';
import { emergencyBookings } from '@/db/schema';

async function main() {
    const sampleBookings = [
        {
            contactName: 'Rajesh Kumar Sharma',
            contactPhone: '9876543210',
            relationship: 'Son',
            locationAddress: 'House No. 45, Banjara Hills Road No. 12, Near Apollo Hospital, Hyderabad',
            city: 'Hyderabad',
            faithTradition: 'Hindu',
            notes: 'Urgent requirement for traditional Hindu last rites. Father passed away this morning. Need pandit and all arrangements by evening.',
            status: 'new',
            priority: 'urgent',
            scheduledAt: null,
            createdAt: Date.now() - (2 * 24 * 60 * 60 * 1000),
            updatedAt: Date.now() - (2 * 24 * 60 * 60 * 1000),
            createdBy: null,
        },
        {
            contactName: 'Priya Nair',
            contactPhone: '8765432109',
            relationship: 'Daughter',
            locationAddress: 'Flat 302, Prestige Towers, Jubilee Hills, Hyderabad',
            city: 'Hyderabad',
            faithTradition: 'Hindu',
            notes: 'Mother passed away peacefully. Need complete funeral arrangements including flower decorations and catering for 100 people.',
            status: 'assigned',
            priority: 'normal',
            scheduledAt: Date.now() + (6 * 60 * 60 * 1000),
            createdAt: Date.now() - (3 * 24 * 60 * 60 * 1000),
            updatedAt: Date.now() - (1 * 24 * 60 * 60 * 1000),
            createdBy: null,
        },
        {
            contactName: 'Mohammed Abdul Rahman',
            contactPhone: '7654321098',
            relationship: 'Brother',
            locationAddress: 'Lane 8, Tolichowki, Behind Mehdipatnam Metro Station, Hyderabad',
            city: 'Hyderabad',
            faithTradition: 'Muslim',
            notes: 'Islamic burial arrangements needed urgently. Brother passed in accident. Family arriving from Dubai tonight.',
            status: 'in_progress',
            priority: 'urgent',
            scheduledAt: Date.now() + (4 * 60 * 60 * 1000),
            createdAt: Date.now() - (1 * 24 * 60 * 60 * 1000),
            updatedAt: Date.now() - (6 * 60 * 60 * 1000),
            createdBy: null,
        },
        {
            contactName: 'Susan Thomas',
            contactPhone: '9123456789',
            relationship: 'Spouse',
            locationAddress: 'Villa 15, Ashok Nagar Colony, Kukatpally, Hyderabad',
            city: 'Hyderabad',
            faithTradition: 'Christian',
            notes: 'Christian funeral service required. Husband was a retired pastor. Need church coordination and burial arrangements.',
            status: 'new',
            priority: 'normal',
            scheduledAt: null,
            createdAt: Date.now() - (5 * 24 * 60 * 60 * 1000),
            updatedAt: Date.now() - (5 * 24 * 60 * 60 * 1000),
            createdBy: null,
        },
        {
            contactName: 'Harpreet Singh Kohli',
            contactPhone: '8234567890',
            relationship: 'Son',
            locationAddress: 'Plot 78, Sector 14, CBD Belapur, Navi Mumbai',
            city: 'Mumbai',
            faithTradition: 'Sikh',
            notes: 'Sikh last rites needed. Father was a respected community leader. Expecting 200+ attendees. Need Gurudwara coordination.',
            status: 'assigned',
            priority: 'normal',
            scheduledAt: Date.now() + (12 * 60 * 60 * 1000),
            createdAt: Date.now() - (4 * 24 * 60 * 60 * 1000),
            updatedAt: Date.now() - (2 * 24 * 60 * 60 * 1000),
            createdBy: null,
        },
        {
            contactName: 'Deepika Reddy',
            contactPhone: '7890123456',
            relationship: 'Sister',
            locationAddress: 'House 22, Sri Nagar Colony, Ameerpet, Hyderabad',
            city: 'Hyderabad',
            faithTradition: null,
            notes: 'Simple cremation arrangements needed. Brother lived alone. No religious ceremonies required as per his wishes.',
            status: 'completed',
            priority: 'normal',
            scheduledAt: Date.now() - (2 * 60 * 60 * 1000),
            createdAt: Date.now() - (7 * 24 * 60 * 60 * 1000),
            updatedAt: Date.now() - (1 * 60 * 60 * 1000),
            createdBy: null,
        },
        {
            contactName: 'Ananya Iyer',
            contactPhone: '6789012345',
            relationship: null,
            locationAddress: '45, 2nd Cross Street, T. Nagar, Chennai',
            city: 'Chennai',
            faithTradition: 'Hindu',
            notes: 'Family friend coordinating arrangements. Elderly person with no immediate family. Need traditional South Indian brahmin customs.',
            status: 'new',
            priority: 'urgent',
            scheduledAt: null,
            createdAt: Date.now() - (6 * 24 * 60 * 60 * 1000),
            updatedAt: Date.now() - (6 * 24 * 60 * 60 * 1000),
            createdBy: null,
        },
        {
            contactName: 'Vikram Joshi',
            contactPhone: '9012345678',
            relationship: 'Friend',
            locationAddress: 'Apartment 501, Green Valley Residency, Gachibowli, Hyderabad',
            city: 'Hyderabad',
            faithTradition: 'Hindu',
            notes: 'Young professional passed suddenly. Parents arriving from Pune tomorrow. Need temporary preservation and full arrangements.',
            status: 'in_progress',
            priority: 'normal',
            scheduledAt: Date.now() + (18 * 60 * 60 * 1000),
            createdAt: Date.now() - (1 * 24 * 60 * 60 * 1000),
            updatedAt: Date.now() - (8 * 60 * 60 * 1000),
            createdBy: null,
        }
    ];

    await db.insert(emergencyBookings).values(sampleBookings);
    
    console.log('✅ Emergency bookings seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});